"""Regenerate ``docs/user_guide/models/supported_models.md`` (zh + en) from the live registry.

This is the single source of truth for the supported-models list. README, index,
support-status, and roadmap all link to the generated file instead of maintaining
their own copies.

The output is fully deterministic: identical registry content produces byte-identical
files. Run this script and commit the diff whenever the registry changes.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys

from omnirt.api import list_available_models
from omnirt.cli.main import render_models_markdown


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "docs" / "user_guide" / "models"
OUTPUT_FILENAME = "supported_models.md"
OUTPUT_FILENAME_EN = "supported_models.en.md"
HEADER_MARKER = "<!-- GENERATED by scripts/generate_models_doc.py \u2014 do not edit -->"


def _registry_hash(specs) -> str:
    payload = "\n".join(sorted(f"{spec.id}\t{spec.task}\t{spec.capabilities.alias_of or ''}" for spec in specs))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _render(specs, *, locale: str) -> str:
    """Render the markdown body with a short locale-aware intro."""

    body = render_models_markdown(specs)
    if locale == "zh":
        intro = (
            "\u672c\u9875\u7531 `scripts/generate_models_doc.py` \u4ece\u6ce8\u518c\u8868\u81ea\u52a8\u751f\u6210\u3002\n"
            "\u4fee\u6539\u8bf7\u52a8 registry\uff0c\u4e0d\u8981\u76f4\u63a5\u6539\u8fd9\u4e2a\u6587\u4ef6\u3002\n\n"
        )
    else:
        intro = (
            "This page is generated from the live registry by `scripts/generate_models_doc.py`.\n"
            "Update the registry, not this file.\n\n"
        )

    body_lines = body.splitlines()
    title = body_lines[0]
    # ``render_models_markdown`` already emits the header marker; strip it so we
    # can attach the registry_hash line immediately below without duplication.
    remainder_lines = [line for line in body_lines[1:] if line.strip() != HEADER_MARKER]
    rest = "\n".join(remainder_lines).lstrip("\n")
    digest = _registry_hash(specs)
    return (
        f"{title}\n\n"
        f"{HEADER_MARKER}\n"
        f"<!-- registry_hash: {digest} -->\n\n"
        f"{intro}"
        f"{rest}"
    )


def write_outputs() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    specs = list_available_models(include_aliases=True)
    for locale, filename in (("zh", OUTPUT_FILENAME), ("en", OUTPUT_FILENAME_EN)):
        target = OUTPUT_DIR / filename
        target.write_text(_render(specs, locale=locale), encoding="utf-8")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the regenerated output differs from what is on disk.",
    )
    args = parser.parse_args(argv)

    specs = list_available_models(include_aliases=True)
    expected = {locale: _render(specs, locale=locale) for locale in ("zh", "en")}
    target_files = {
        "zh": OUTPUT_DIR / OUTPUT_FILENAME,
        "en": OUTPUT_DIR / OUTPUT_FILENAME_EN,
    }

    if args.check:
        drift = []
        for locale, path in target_files.items():
            current = path.read_text(encoding="utf-8") if path.is_file() else ""
            if current != expected[locale]:
                try:
                    drift.append(str(path.relative_to(REPO_ROOT)))
                except ValueError:
                    drift.append(str(path))
        if drift:
            print("models doc is stale; regenerate with scripts/generate_models_doc.py", file=sys.stderr)
            for item in drift:
                print(f"  - {item}", file=sys.stderr)
            return 1
        return 0

    write_outputs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
